.travis.yml
package-lock.json
package.json

customize package.json & travis.yml

---

package.json
server/db/db.js
server/db/models/user.js

User table

---

server/db/models/product.js

product model

---

server/db/models/order.js

Omusinov branch

---

server/db/models/index.js
server/db/models/order_product.js
server/db/models/product.js

order-product

---

server/db/models/index.js
server/db/models/order.js
server/db/models/order_product.js

associations

---

seed.js

---
Created seed file for product model

added products seed

---

script/seed.js
server/db/models/product.js

seeded db with product and user

---

package-lock.json
package.json
server/api/products.spec.js
server/api/users.spec.js
server/db/models/user.spec.js

quick test spec for all products backend

product api test specs complete

---

script/seed.js
server/api/users.js
server/db/models/product.js

minor database changes

---

.gitignore
server/api/products.spec.js
server/api/users.spec.js
server/db/models/product.js
server/db/models/user.spec.js

Fix user test

---

client/components/SingleProduct.js
client/routes.js

singleProduct

---

client/components/Cart.js
client/components/ProductRow.js
client/components/navbar.js
client/routes.js
client/store/cart.js
server/api/cart.js
server/api/index.js
server/api/users.js

some stuff

---

client/routes.js
server/db/models/product.js

fix freeze database name error

---

server/db/models/user.js

fixed login issue

---

client/components/SingleProduct.js

solve-singleProduct-price

---

server/api/gatekeeper.js
server/api/users.js
server/db/models/user.js

added router security

---

client/store/cart.js
package.json

Added reducer for cart in store, but left it commented out for group approval because it will interfere with what was already there.

added reducers for cart including localStorage

---

client/components/SingleProduct.js
server/index.js

local storage

---

client/components/Cart.js
client/components/Checkout.js
client/components/EachCart.js
client/components/SingleProduct.js
client/routes.js
client/store/cart.js
client/store/index.js

Sam local cart

---

client/components/Checkout.js

checkout-form

---

client/components/navbar.js
server/api/cart.js
server/db/models/index.js

routes for cart

---

client/components/auth-form.js
client/store/user.js
server/api/orders.js

Sign up form takes all necessary fields to store user into the database. Redirects (for now) to all products page after sign-up is complete

sign up form is working and saves to database

---

client/components/Cart.js
client/components/EachCart.js
client/components/ProductRow.js
client/store/cart.js

quantity selector in home page &  cart page + subtotal on cart page

---

public/index.html
public/style.sass

bulma working with cdn

---

client/components/CheckoutInfo.js
client/components/ProductRow.js

clear cart after purchase

---

client/components/ProductList.js
client/components/auth-form-signup.js
client/store/user.js

redirect to product page after sign in

---

client/components/CheckoutInfo.js
client/components/ProductRow.js

add $ to product and modify checkout page

---

client/components/CheckoutInfo.js

made total.toFix(2)
